# Generated by Django 3.2.9 on 2021-11-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hello',
            options={'verbose_name_plural': 'Hello'},
        ),
    ]
