apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: senjespakk/react-app
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "250Mi"
              cpu: "0.3"
            limits:
              memory: "515Mi"
              cpu: "0.5"   
                                    
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: ClusterIP
  selector:
    app: react-app
  ports:
    - port: 3000
